on:
  workflow_dispatch:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main

  schedule:
  - cron: "0 2 * * 1-5"

  
jobs:
  test:
    name: WDIO tests
    runs-on: ubuntu-22.04
    steps:
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
          node-version: '20.x'
          
       - name: Install Dependencies
          run:npm install
        
       - name: Run Chrome Tests
          run:npm run wdio
      
